apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolistapp
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: todolistapp
  template:
    metadata:
      labels:
        app: todolistapp
    spec:
      containers:
      - name: todolistapp
        image: mx-queretaro-1.ocir.io/axvndkwpufiq/todolistrepo:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: REACT_APP_CLERK_PUBLISHABLE_KEY
            valueFrom:
              secretKeyRef:
                name: clerksecret
                key: api-key
      imagePullSecrets:
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: todolistapp-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: todolistapp